export const WCAG_MAPPINGS: Record<
  string,
  { id: string; level: "A" | "AA" | "AAA"; name: string; description: string }
> = {
  "image-alt": {
    id: "1.1.1",
    level: "A",
    name: "Non-text Content",
    description:
      "All non-text content that is presented to the user has a text alternative",
  },
  "button-name": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description:
      "For all user interface components, the name and role can be programmatically determined",
  },
  "link-name": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description: "Link purpose can be determined from link text",
  },
  "color-contrast": {
    id: "1.4.3",
    level: "AA",
    name: "Contrast (Minimum)",
    description:
      "Text and images of text have a contrast ratio of at least 4.5:1",
  },
  label: {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description:
      "Information and relationships conveyed through presentation can be programmatically determined",
  },
  "html-has-lang": {
    id: "3.1.1",
    level: "A",
    name: "Language of Page",
    description:
      "The default human language of each page can be programmatically determined",
  },
  "document-title": {
    id: "2.4.2",
    level: "A",
    name: "Page Titled",
    description: "Web pages have titles that describe topic or purpose",
  },
  "heading-order": {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "Headings are used in a logical order",
  },
  region: {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "All content is contained within landmark regions",
  },
  "aria-valid-attr": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description: "ARIA attributes are used correctly",
  },
  "aria-required-attr": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description: "Elements with ARIA roles have required ARIA attributes",
  },
  "aria-roles": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description: "Valid ARIA roles are used",
  },
  "meta-viewport": {
    id: "1.4.4",
    level: "AA",
    name: "Resize Text",
    description: "Users can zoom in the viewport",
  },
  tabindex: {
    id: "2.4.3",
    level: "A",
    name: "Focus Order",
    description:
      "Elements receive focus in an order that preserves meaning and operability",
  },
  "duplicate-id": {
    id: "4.1.1",
    level: "A",
    name: "Parsing",
    description: "No id attributes have duplicate values",
  },
  bypass: {
    id: "2.4.1",
    level: "A",
    name: "Bypass Blocks",
    description:
      "A mechanism is available to bypass blocks of repeated content",
  },
  "scrollable-region-focusable": {
    id: "2.1.1",
    level: "A",
    name: "Keyboard",
    description: "All functionality available via keyboard",
  },
  "frame-focusable-content": {
    id: "2.1.1",
    level: "A",
    name: "Keyboard",
    description: "Content within iframes is keyboard accessible",
  },
  "focus-order-semantics": {
    id: "2.4.3",
    level: "A",
    name: "Focus Order",
    description: "Focus order is logical and meaningful",
  },
  "video-caption": {
    id: "1.2.2",
    level: "A",
    name: "Captions (Prerecorded)",
    description: "Captions are provided for video content",
  },
  "audio-caption": {
    id: "1.2.1",
    level: "A",
    name: "Audio-only and Video-only (Prerecorded)",
    description: "Transcripts are provided for audio content",
  },
  "no-autoplay-audio": {
    id: "1.4.2",
    level: "A",
    name: "Audio Control",
    description: "Audio does not autoplay or can be paused",
  },
  "object-alt": {
    id: "1.1.1",
    level: "A",
    name: "Non-text Content",
    description: "Alternative content is provided for objects",
  },
  "svg-img-alt": {
    id: "1.1.1",
    level: "A",
    name: "Non-text Content",
    description: "SVG images have accessible names",
  },
  "td-headers-attr": {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "Data table cells are properly associated with headers",
  },
  "th-has-data-cells": {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "Table headers have associated data cells",
  },
  "scope-attr-valid": {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "Scope attributes are used correctly in tables",
  },
  "table-fake-caption": {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "Tables use caption elements instead of fake captions",
  },
  "definition-list": {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "Definition lists only contain dt and dd elements",
  },
  list: {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "Lists only contain list items",
  },
  listitem: {
    id: "1.3.1",
    level: "A",
    name: "Info and Relationships",
    description: "List items are inside appropriate list containers",
  },
  "nested-interactive": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description: "Interactive elements are not nested",
  },
  "input-image-alt": {
    id: "1.1.1",
    level: "A",
    name: "Non-text Content",
    description: "Image input buttons have alt text",
  },
  "select-name": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description: "Select elements have accessible names",
  },
  "autocomplete-valid": {
    id: "1.3.5",
    level: "AA",
    name: "Identify Input Purpose",
    description: "Valid autocomplete attributes are used",
  },
  "frame-title": {
    id: "4.1.2",
    level: "A",
    name: "Name, Role, Value",
    description: "Frames have title attributes",
  },
  "valid-lang": {
    id: "3.1.2",
    level: "AA",
    name: "Language of Parts",
    description: "Language attributes use valid language codes",
  },
  marquee: {
    id: "2.2.2",
    level: "A",
    name: "Pause, Stop, Hide",
    description: "Marquee elements should not be used",
  },
  blink: {
    id: "2.2.2",
    level: "A",
    name: "Pause, Stop, Hide",
    description: "Blink elements should not be used",
  },
};

export const RULE_TO_CATEGORY: Record<string, string> = {
  "image-alt": "images",
  "button-name": "interactive",
  "link-name": "interactive",
  "color-contrast": "color",
  label: "forms",
  "html-has-lang": "document",
  "document-title": "document",
  "heading-order": "structure",
  region: "structure",
  "aria-valid-attr": "aria",
  "aria-required-attr": "aria",
  "aria-roles": "aria",
  "meta-viewport": "document",
  tabindex: "technical",
  "duplicate-id": "technical",
  bypass: "interactive",
  "scrollable-region-focusable": "interactive",
  "frame-focusable-content": "interactive",
  "focus-order-semantics": "interactive",
  "video-caption": "images",
  "audio-caption": "images",
  "no-autoplay-audio": "images",
  "object-alt": "images",
  "svg-img-alt": "images",
  "td-headers-attr": "structure",
  "th-has-data-cells": "structure",
  "scope-attr-valid": "structure",
  "table-fake-caption": "structure",
  "definition-list": "structure",
  list: "structure",
  listitem: "structure",
  "nested-interactive": "interactive",
  "input-image-alt": "forms",
  "select-name": "forms",
  "autocomplete-valid": "forms",
  "frame-title": "document",
  "valid-lang": "document",
  marquee: "technical",
  blink: "technical",
};
